Repository y10b/6-Photo-2-FE, pull requests merged in 2025-06, with the labels that each got.

#81 fix: 외부 클릭 시 모달 닫기
  src/components/layout/Header.jsx
  src/components/layout/ProfileModal.jsx
Labels: 🩹Fix

#82 [Refactor] 응답메시지통일, 헤더/구글닉넴구글추가, 배포서버로 설정
  src/api/axiosInstance.js
  src/app/auth/callback/page.jsx
  src/app/auth/login/page.jsx
  src/app/auth/signup/page.jsx
  src/components/layout/Header.jsx
  src/lib/api/auth-service.js
  src/lib/fetchClient.js
  src/providers/AuthProvider.jsx
Labels: 🛠️Refactor

#85 fix: 데스크탑 검색/ 필터 추가
  src/components/market/MyCardsSellBottomSheet.jsx
Labels: 🩹Fix

#86 feat: 비회원도 마켓 접근 가능하도록 수정 및 비회원 클릭 시 모달 표시
  src/app/market/page.jsx
  src/components/market/MyCardsSellBottomSheet.jsx
  src/lib/api/marketApi.js
  src/providers/RouteGuard.jsx
Labels: ⭐Feat, ⚙️Chore

#88 feat: 마이 갤러리에서 카드 선택시 판매모달로 이어지도록 연결
  src/app/my-gallery/page.jsx
Labels: ⭐Feat

#90 feat: 가격 인풋 제한 로직 추가 및 페이지네이션 오류 해결
  src/app/my-gallery/create/page.jsx
  src/app/my-gallery/page.jsx
  src/app/sale/page.jsx
Labels: 🩹Fix, ⭐Feat

#93 마켓, 갤러리, 판매 페이지 리팩토링
  README.md
  src/app/market/page.jsx
  src/app/my-gallery/page.jsx
  src/app/sale/page.jsx
  src/hooks/useLocalUser.js
  src/hooks/useMarketInfiniteCards.js
  src/lib/api/galleryApi.js
  src/lib/api/marketApi.js
  src/utils/filterOptions.js
Labels: 🛠️Refactor

#97 필터 바텀시트 리팩토링 및 README 작성
  README.md
  public/dev/filterbottomsheet.png
  public/dev/loadingspinner.png
  public/dev/marketplace.png
  public/dev/mygallery.png
  public/dev/pagination.png
  src/components/market/FilterBottomSheet.jsx
  src/utils/filterOptions.js
Labels: 📜Docs, 🛠️Refactor

#98 fix: 생성 제한 토스트 안 뜨는 문제 해결
  src/app/my-gallery/page.jsx
  src/components/common/ToastMessage.jsx
Labels: 🩹Fix

#100 fix: 마이갤러리 드롭다운 오타 수정
  src/app/my-gallery/page.jsx
Labels: 🩹Fix

#107 fix: 판매 오류 수정
  README.md
  src/components/market/EditCardModal.jsx
  src/components/market/SellCardRegistrationBottomSheet.jsx
  src/components/ui/card/cardProfile/SellerCardItem.jsx
Labels: 🩹Fix

#108 docs: README.md 수정
  README.md
Labels: 📜Docs
