Repository y10b/6-Photo-2-FE, pull requests merged in 2025-05, with the labels that each got.

#6 Feature/nav 네비게이션 구현
  public/icons/ic_alarm_default.svg
  public/icons/ic_menu.svg
  public/logo.svg
  src/app/layout.js
  src/components/layout/Header.jsx
Labels: feat

#11 feat: landing5 페이지 구현
  package-lock.json
  package.json
  public/images/landing/landing5.svg
  src/app/globals.css
  src/app/page.js
Labels: ⭐Feat

#21 feat: wrapperLayout 구현
  src/app/layout.js
  src/app/page.js
  src/components/layout/Header.jsx
  src/components/layout/WrapperLayout.jsx
Labels: ⭐Feat

#22 [기능] Input 컴포넌트 텍스트 필드 30자 제한 추가
  src/app/auth/login/page.jsx
  src/app/auth/signup/page.jsx
  src/components/layout/Header.jsx
  src/components/ui/input/Input.jsx
Labels: 🩹Fix

#23 feat: 마켓플레이스 메인 레이아웃 구성
  package-lock.json
  package.json
  public/icons/ic_close_gray.svg
  public/icons/ic_down.svg
  public/icons/ic_exchange.svg
  public/icons/ic_filter.svg
  public/icons/ic_reset.svg
  src/app/layout.js
  src/app/market/page.js
  src/components/market/FilterBottomSheet.jsx
  src/lib/api/marketApi.js
  src/providers/ReactQueryProvider.jsx
Labels: ⭐Feat

#26 Feature/marketplace
  src/app/market/page.js
  src/components/market/FilterBottomSheet.jsx
  src/lib/api/marketApi.js
Labels: 🩹Fix

#28 Feature/marketplace
  public/icons/ic_corner.svg
  public/icons/ic_left.svg
  public/icons/ic_right.svg
  src/app/market/page.js
  src/app/not-found.jsx
  src/components/market/Pagination.jsx
Labels: 🩹Fix, ⭐Feat

#29 fix: api url 수정
  .prettierrc
  src/lib/api/shop.js
Labels: 🩹Fix

#32 feat: 반응형 모달 시스템 구현 및 AlertModal 통합
  src/app/auth/login/page.jsx
  src/app/auth/signup/page.jsx
  src/app/layout.js
  src/app/market/page.jsx
  src/components/common/Button.jsx
  src/components/common/Modal.jsx
  src/components/market/MyCardsSellBottomSheet.jsx
  src/components/modal/ModalContext.jsx
  src/components/modal/ModalRenderer.jsx
  src/components/modal/ResponsiveModalWrapper.jsx
  src/components/modal/layout/AlertModal.jsx
  src/components/modal/layout/BottomSheetModal.jsx
  src/components/modal/layout/DesktopModal.jsx
  src/components/modal/layout/FullScreenModal.jsx
  src/components/ui/card/cardProfile/BuyerCardItem.jsx
  src/hooks/useMediaQuery.js
Labels: ⭐Feat

#35 [인증] 회원가입 & 로그인 프론트엔드 연결
  package-lock.json
  package.json
  src/api/auth.api.js
  src/api/axiosInstance.js
  src/app/auth/login/page.jsx
  src/app/auth/signup/page.jsx
  src/app/layout.js
  src/app/page.jsx
  src/app/providers.jsx
  src/components/common/Modal.jsx
  src/components/layout/Header.jsx
  src/components/ui/input/Input.jsx
  src/providers/AuthProvider.jsx
  src/providers/RouteGuard.jsx
Labels: ⭐Feat

#36 feat: 알림 UI 구현
  package-lock.json
  public/icons/ic_m_close.svg
  src/components/layout/Header.jsx
  src/components/layout/NotificationModal.jsx
Labels: ⭐Feat

#41 style: 마이갤러리 UI 디자인 수정 및 레이아웃 개선
  src/app/my-gallary/page.jsx
  src/components/ui/input/DropdownInput.jsx
Labels: 🩹Fix, 🎀Style

#47 포토카드 생성 기능 및 UI 개선사항 반영
  public/icons/ic_back.svg
  src/app/market/page.jsx
  src/app/my-gallery/create/page.jsx
  src/app/my-gallery/page.jsx
  src/components/modal/layout/FullScreenModal.jsx
  src/components/ui/card/cardOverview/CardImage.jsx
  src/components/ui/input/DropdownInput.jsx
  src/components/ui/input/UploadInput.jsx
  src/lib/api/galleryApi.js
  src/lib/api/marketApi.js
Labels: 🩹Fix, ⭐Feat

#49 test: 배포 주소 수정 후 fetch 테스트
  src/lib/api/galleryApi.js
  src/lib/api/marketApi.js
Labels: 📊Test

#58 포토카드 생성 제한, 랜덤 포인트 모달, 로딩 스피너 추가 및 드롭다운 UI 개선
  public/icons/ic_alert.svg
  src/app/my-gallery/page.jsx
  src/components/common/ToastMessage.jsx
  src/components/modal/ModalRenderer.jsx
  src/components/modal/layout/PointModal.jsx
  src/components/ui/LoadingSpinner.jsx
  src/components/ui/card/cardOverview/CardOverview.jsx
  src/components/ui/input/DropdownInput.jsx
  src/lib/api/galleryApi.js
  src/providers/RouteGuard.jsx
Labels: ⭐Feat, 🎀Style, 🛠️Refactor

#67 [기능] 포인트 뽑기 기능 전체 구현 (UI + API 연동 + 쿨타임 모달)
  package-lock.json
  public/images/box1.png
  public/images/box2.png
  public/images/box3.png
  public/images/point-lg.png
  public/images/point-sm.png
  src/api/user.api.js
  src/components/common/PointDrawModal.jsx
  src/components/layout/AppInitializer.jsx
  src/components/layout/WrapperLayout.jsx
  src/components/modal/ModalRenderer.jsx
  src/providers/AuthProvider.jsx
  src/providers/RouteGuard.jsx
Labels: ⭐Feat

#74 [리팩토링] 회원가입 인풋 개선 및 fetch 전환, 이미지 최적화
  package-lock.json
  package.json
  src/api/auth.api.js
  src/api/user.api.js
  src/app/auth/login/page.jsx
  src/app/auth/signup/page.jsx
  src/components/common/PointDrawModal.jsx
  src/components/layout/AppInitializer.jsx
  src/components/ui/input/AuthInput.jsx
  src/components/ui/input/Input.jsx
  src/components/ui/input/index.js
  src/hooks/memo
  src/lib/api/auth-service.js
  src/lib/api/user-service.js
  src/lib/fetchClient.js
  src/providers/AuthProvider.jsx
  src/schemas/login.schema.js
  src/schemas/signup.schema.js
Labels: 🛠️Refactor
